@startuml controller states

state Develop #LightGreen: Build-up production
state Rebuild #LightGreen: Rebuild economy after losses
state Defend #LightGreen: Defend against attacks
state BuildUp #LightGreen: Build an army that\ncounters enemy strategy
state Routing: Decide on next general strategy

state ExpandPrepare #LightBlue: Preparing forces\nto secure expand location
state ExpandSecure #LightBlue: Move to selected location\nand secure it
state ExpandBuild #LightBlue: Build expand\non secured location

state Exterminate #LightCoral: Attack the enemy

[*] --> Routing: Initial state

Defend --> Rebuild: Attack countered\nDamage is not severe
Defend -up-> Routing: Attack countered\nDamage is too severe

Develop --> BuildUp: Economy\nfunctioning
Develop -down-> Defend: Attacked
Develop -left-> ExpandPrepare: Not enough resources to\nperform settlement development

BuildUp -down-> Exterminate: Army gathered\nOR\nTimeout Exceeded
BuildUp --> Defend: Attacked
BuildUp --> Develop: Impossible to produce\nany combat unit
BuildUp -left-> ExpandPrepare: Not enough resources\nto produce necessary army

Rebuild --> BuildUp: Economy\nRestored
Rebuild --> Defend: Attacked

ExpandPrepare --> ExpandSecure: Forces gathered
ExpandPrepare -down-> Defend: Attacked

ExpandSecure --> ExpandBuild: Expand secured
ExpandSecure -down-> Defend: Attacked
ExpandSecure -up-> Routing: Failed to\nsecure expand

ExpandBuild -up-> Routing: Expand up and running
ExpandBuild -down-> Defend: Attacked

Exterminate --> [*]: Enemy defeated
Exterminate -up-> Routing: Army slain\nOR\nTimeout exceeded
Exterminate --> Defend: Main or expand attacked

Routing -down-> BuildUp: Current economy is enough\nto attack
Routing -down-> Develop: Need to develop economy
Routing -down-> ExpandPrepare: Not enough resources

legend
| **Color** | **Meaning** |
|<#LightGreen>| Exploit |
|<#LightBlue>| Expand |
|<#LightCoral>| Exterminate |
endlegend

@enduml